import { StyleSheet } from 'react-native'
import { colors, fonts, radii, shadow, spacing } from '../theme'

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  shell: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  loadingShell: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bg,
  },
  header: {
    height: 56,
    paddingHorizontal: 20,
    borderBottomWidth: 2,
    borderBottomColor: colors.ink,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logo: {
    fontFamily: fonts.display,
    fontSize: 25,
    letterSpacing: 0.9,
    color: colors.ink,
    textTransform: 'uppercase',
  },
  logoAccent: {
    color: colors.green,
  },
  headerMeta: {
    color: colors.inkFaint,
    fontFamily: fonts.label,
    fontSize: 12,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    flexShrink: 1,
  },
  page: {
    paddingHorizontal: 20,
    paddingTop: 28,
    paddingBottom: 112,
  },
  kicker: {
    color: colors.greenDark,
    fontFamily: fonts.label,
    fontSize: 13,
    letterSpacing: 1.5,
    marginBottom: spacing.sm,
    textTransform: 'uppercase',
  },
  hero: {
    color: colors.ink,
    fontFamily: fonts.display,
    fontSize: 42,
    letterSpacing: -0.4,
    lineHeight: 39,
    marginBottom: spacing.sm,
    textTransform: 'uppercase',
  },
  heroCompact: {
    fontSize: 36,
    lineHeight: 35,
  },
  body: {
    color: colors.inkSoft,
    fontFamily: fonts.body,
    fontSize: 17,
    lineHeight: 26,
    marginBottom: 32,
  },
  summaryBlock: {
    marginBottom: 18,
  },
  liveModeCard: {
    backgroundColor: colors.bg2,
    borderColor: colors.border,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  liveModeCardActive: {
    borderColor: 'rgba(95,160,97,0.4)',
    backgroundColor: '#f8f4ea',
  },
  liveModeTitle: {
    color: colors.ink,
    fontFamily: fonts.label,
    fontSize: 13,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  liveModeTitleActive: {
    color: colors.greenDark,
  },
  liveModeControl: {
    alignItems: 'center',
    flexShrink: 0,
  },
  liveModeSwitchTrack: {
    width: 42,
    height: 24,
    borderRadius: 999,
    backgroundColor: '#ddd6c8',
    padding: 3,
    justifyContent: 'center',
  },
  liveModeSwitchTrackActive: {
    backgroundColor: colors.green,
  },
  liveModeSwitchThumb: {
    width: 18,
    height: 18,
    borderRadius: 999,
    backgroundColor: colors.bg,
  },
  liveModeSwitchThumbActive: {
    transform: [{ translateX: 18 }],
  },
  summaryTitle: {
    color: colors.inkFaint,
    fontFamily: fonts.label,
    fontSize: 13,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  summaryPills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  summaryPill: {
    backgroundColor: colors.bg2,
    borderColor: colors.border,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  summaryPillActive: {
    backgroundColor: colors.ink,
    borderColor: colors.ink,
  },
  summaryPillText: {
    color: colors.inkSoft,
    fontFamily: fonts.label,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  summaryPillTextActive: {
    color: colors.bg,
  },
  dayTabs: {
    gap: 8,
    paddingBottom: spacing.sm,
  },
  dayTab: {
    minWidth: 86,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bg2,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  dayTabActive: {
    borderWidth: 2,
    borderColor: colors.ink,
    backgroundColor: colors.bg,
  },
  dayTabText: {
    color: colors.inkSoft,
    fontFamily: fonts.label,
    fontSize: 13,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  dayTabTextActive: {
    color: colors.ink,
  },
  dayTabSubtext: {
    color: colors.inkFaint,
    fontFamily: fonts.bodySemi,
    fontSize: 11,
  },
  dayTabSubtextActive: {
    color: colors.greenDark,
  },
  filterHint: {
    color: colors.inkSoft,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 0,
  },
  categoryTabs: {
    gap: 6,
    paddingBottom: 20,
    paddingTop: 16,
  },
  categoryTab: {
    flexShrink: 0,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 4,
    backgroundColor: colors.bg2,
  },
  categoryTabActive: {
    backgroundColor: colors.ink,
  },
  categoryTabText: {
    color: colors.inkSoft,
    fontFamily: fonts.label,
    fontSize: 13,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  categoryTabTextActive: {
    color: colors.bg,
  },
  dealGroupList: {
    gap: 12,
  },
  sectionKicker: {
    color: colors.inkFaint,
    fontFamily: fonts.label,
    fontSize: 12,
    letterSpacing: 1.3,
    textTransform: 'uppercase',
  },
  sectionSubcopy: {
    color: colors.inkSoft,
    fontFamily: fonts.body,
    fontSize: 14,
    marginBottom: 12,
  },
  noticeDemo: {
    backgroundColor: colors.bg2,
    borderColor: colors.borderStrong,
    borderRadius: radii.md,
    borderWidth: 1,
    marginBottom: spacing.lg,
    padding: spacing.md,
  },
  noticeLive: {
    backgroundColor: colors.greenLight,
    borderColor: 'rgba(95,160,97,0.32)',
    borderRadius: radii.md,
    borderWidth: 1,
    marginBottom: spacing.lg,
    padding: spacing.md,
  },
  noticeTitle: {
    color: colors.ink,
    fontFamily: fonts.label,
    fontSize: 14,
    letterSpacing: 1.1,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  noticeText: {
    color: colors.inkSoft,
    fontFamily: fonts.bodySemi,
    fontSize: 14,
    lineHeight: 20,
  },
  loadingCard: {
    alignItems: 'center',
    backgroundColor: colors.bg2,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.xl,
  },
  buttonGap: {
    height: spacing.sm,
  },
  input: {
    backgroundColor: colors.bg2,
    borderWidth: 2,
    borderColor: colors.borderStrong,
    borderRadius: radii.sm,
    color: colors.ink,
    fontFamily: fonts.body,
    fontSize: 16,
    padding: 15,
    marginBottom: spacing.md,
  },
  googleButton: {
    width: '100%',
    padding: 16,
    backgroundColor: colors.bg2,
    borderColor: colors.borderStrong,
    borderRadius: radii.sm,
    borderWidth: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginBottom: 12,
  },
  googleMark: {
    color: colors.ink,
    fontFamily: fonts.bodyBold,
    fontSize: 18,
  },
  googleButtonText: {
    color: colors.ink,
    fontFamily: fonts.display,
    fontSize: 17,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.borderStrong,
  },
  dividerText: {
    color: colors.inkFaint,
    fontFamily: fonts.label,
    fontSize: 12,
    letterSpacing: 1.3,
    textTransform: 'uppercase',
  },
  primaryButton: {
    backgroundColor: colors.green,
    borderRadius: radii.sm,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  buttonDisabled: {
    backgroundColor: colors.inkFaint,
  },
  primaryButtonText: {
    color: '#fff',
    fontFamily: fonts.display,
    fontSize: 17,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  secondaryButton: {
    borderColor: colors.borderStrong,
    borderWidth: 2,
    borderRadius: radii.sm,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  secondaryButtonText: {
    color: colors.inkSoft,
    fontFamily: fonts.display,
    fontSize: 16,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
    gap: spacing.sm,
  },
  sectionTitle: {
    color: colors.ink,
    fontFamily: fonts.display,
    fontSize: 18,
    textTransform: 'uppercase',
    flexShrink: 1,
  },
  sectionMeta: {
    color: colors.inkFaint,
    fontFamily: fonts.label,
    fontSize: 13,
  },
  dealCard: {
    backgroundColor: colors.bg2,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.md,
    padding: spacing.md,
    marginBottom: spacing.md,
    ...shadow.card,
  },
  businessCard: {
    backgroundColor: colors.bg2,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    marginBottom: spacing.md,
    overflow: 'hidden',
    ...shadow.card,
  },
  businessPhotoWrap: {
    height: 180,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: colors.bg3,
  },
  businessPhoto: {
    width: '100%',
    height: '100%',
  },
  businessPhotoFallback: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.forest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoCategoryPill: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: colors.ink,
    color: colors.bg,
    fontFamily: fonts.label,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 3,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
    overflow: 'hidden',
  },
  photoFavoritePill: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: 'rgba(15,15,15,0.78)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  photoFavoritePillActive: {
    backgroundColor: colors.green,
  },
  photoFavoriteText: {
    color: '#fff',
    fontFamily: fonts.label,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  photoMultiPill: {
    position: 'absolute',
    top: 50,
    right: 12,
    backgroundColor: colors.green,
    color: '#fff',
    fontFamily: fonts.label,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 3,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
    overflow: 'hidden',
  },
  photoFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15,15,15,0.84)',
    paddingHorizontal: 14,
    paddingBottom: 12,
    paddingTop: 10,
  },
  photoBusinessName: {
    color: '#fff',
    fontFamily: fonts.display,
    fontSize: 21,
    letterSpacing: 0.2,
    lineHeight: 23,
    marginBottom: 3,
    textTransform: 'uppercase',
  },
  photoAddress: {
    color: 'rgba(255,255,255,0.76)',
    fontFamily: fonts.body,
    fontSize: 12,
  },
  businessDealList: {
    backgroundColor: colors.bg2,
  },
  businessDealRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  businessDealRowBorder: {
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
  },
  businessDealCopy: {
    flex: 1,
    minWidth: 0,
  },
  availabilityPill: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontFamily: fonts.label,
    fontSize: 11,
    letterSpacing: 1,
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  availabilityActive: {
    backgroundColor: '#E8F8EF',
    color: colors.greenDark,
  },
  availabilityLater: {
    backgroundColor: '#FFF3CD',
    color: '#92600A',
  },
  availabilityCooldown: {
    backgroundColor: colors.bg3,
    color: colors.inkFaint,
  },
  businessDealRowDisabled: {
    opacity: 0.55,
  },
  rowAction: {
    color: colors.inkFaint,
    fontFamily: fonts.label,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
    flexShrink: 0,
  },
  rowActionButton: {
    backgroundColor: colors.green,
    borderRadius: 4,
    color: '#fff',
    fontFamily: fonts.display,
    fontSize: 13,
    letterSpacing: 1,
    overflow: 'hidden',
    paddingHorizontal: 16,
    paddingVertical: 8,
    textTransform: 'uppercase',
    flexShrink: 0,
  },
  dealImage: {
    width: '100%',
    height: 142,
    borderRadius: radii.sm,
    marginBottom: spacing.md,
    backgroundColor: colors.bg3,
  },
  dealImageFallback: {
    width: '100%',
    height: 122,
    borderRadius: radii.sm,
    marginBottom: spacing.md,
    backgroundColor: colors.forest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dealImageText: {
    color: colors.green,
    fontFamily: fonts.display,
    fontSize: 15,
    letterSpacing: 1.3,
    textTransform: 'uppercase',
  },
  dealTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
    gap: spacing.sm,
  },
  categoryPill: {
    alignSelf: 'flex-start',
    backgroundColor: colors.greenLight,
    borderRadius: 999,
    color: colors.greenDark,
    fontFamily: fonts.label,
    fontSize: 12,
    letterSpacing: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
    textTransform: 'uppercase',
    flexShrink: 1,
    maxWidth: '72%',
  },
  inlineFavoritePill: {
    backgroundColor: 'rgba(15,15,15,0.78)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  inlineFavoritePillActive: {
    backgroundColor: colors.green,
  },
  inlineFavoriteText: {
    color: '#fff',
    fontFamily: fonts.label,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  cardTitle: {
    color: colors.ink,
    fontFamily: fonts.display,
    fontSize: 25,
    letterSpacing: 0.1,
    lineHeight: 27,
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  dealText: {
    color: colors.greenDark,
    fontFamily: fonts.bodyBold,
    fontSize: 15,
    lineHeight: 21,
    marginBottom: 8,
  },
  muted: {
    color: colors.inkFaint,
    fontFamily: fonts.bodySemi,
    fontSize: 13,
  },
  empty: {
    paddingHorizontal: spacing.md,
    paddingVertical: 64,
  },
  emptyTitle: {
    color: colors.ink,
    fontFamily: fonts.display,
    fontSize: 32,
    letterSpacing: 0.1,
    lineHeight: 32,
    marginBottom: spacing.sm,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  emptyText: {
    color: colors.inkFaint,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  historyCard: {
    backgroundColor: colors.bg2,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  historyList: {
    gap: spacing.md,
  },
  historyBody: {
    flex: 1,
    minWidth: 0,
  },
  statusPill: {
    backgroundColor: colors.greenLight,
    borderRadius: 999,
    color: colors.greenDark,
    fontFamily: fonts.label,
    fontSize: 11,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
    textTransform: 'uppercase',
    flexShrink: 0,
  },
  accountCard: {
    backgroundColor: colors.bg2,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  accountSubCard: {
    backgroundColor: colors.bg2,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  subCardEyebrow: {
    color: colors.inkFaint,
    fontFamily: fonts.label,
    fontSize: 12,
    letterSpacing: 1.1,
    marginBottom: 14,
    textTransform: 'uppercase',
  },
  subCardText: {
    color: colors.inkSoft,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 20,
  },
  accountHeroCard: {
    backgroundColor: colors.forest,
    borderRadius: radii.md,
    marginBottom: spacing.md,
    padding: spacing.md,
  },
  accountHeroEyebrow: {
    color: colors.green,
    fontFamily: fonts.label,
    fontSize: 11,
    letterSpacing: 1.1,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  accountHeroTitle: {
    color: colors.bg,
    fontFamily: fonts.displayBold,
    fontSize: 34,
    lineHeight: 34,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  accountHeroText: {
    color: 'rgba(255,255,255,0.78)',
    fontFamily: fonts.body,
    fontSize: 15,
    lineHeight: 22,
  },
  accountStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: spacing.md,
  },
  accountStatCard: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: radii.sm,
    borderWidth: 1,
    flex: 1,
    minHeight: 84,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  accountStatValue: {
    color: colors.bg,
    fontFamily: fonts.displayBold,
    fontSize: 26,
    lineHeight: 28,
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  accountStatLabel: {
    color: 'rgba(255,255,255,0.65)',
    fontFamily: fonts.label,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  accountRow: {
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingVertical: 12,
  },
  accountLabel: {
    color: colors.inkSoft,
    fontFamily: fonts.bodySemi,
    fontSize: 14,
    flexShrink: 0,
  },
  accountValue: {
    color: colors.ink,
    fontFamily: fonts.bodyBold,
    fontSize: 14,
    flex: 1,
    textAlign: 'right',
  },
  accountHistoryRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingVertical: 12,
  },
  accountHistoryRowBorder: {
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
  },
  accountHistoryCopy: {
    flex: 1,
    minWidth: 0,
  },
  accountHistoryTitle: {
    color: colors.ink,
    fontFamily: fonts.bodyBold,
    fontSize: 14,
    marginBottom: 2,
  },
  accountHistoryDeal: {
    color: colors.greenDark,
    fontFamily: fonts.bodySemi,
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 4,
  },
  accountHistoryDate: {
    color: colors.inkFaint,
    fontFamily: fonts.bodySemi,
    fontSize: 12,
  },
  creatorCard: {
    backgroundColor: '#f7f2e7',
    borderColor: '#decfa2',
    borderRadius: radii.md,
    borderWidth: 1,
    marginBottom: spacing.md,
    padding: spacing.md,
  },
  creatorPill: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(28,28,26,0.08)',
    borderRadius: 999,
    color: colors.ink,
    fontFamily: fonts.label,
    fontSize: 12,
    letterSpacing: 1,
    marginBottom: 12,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 4,
    textTransform: 'uppercase',
  },
  creatorTitle: {
    color: colors.ink,
    fontFamily: fonts.displayBold,
    fontSize: 24,
    lineHeight: 24,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  creatorText: {
    color: colors.inkSoft,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 14,
  },
  creatorSteps: {
    gap: 8,
    marginBottom: 14,
  },
  creatorStepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(255,255,255,0.46)',
    borderColor: 'rgba(15,15,15,0.08)',
    borderRadius: radii.sm,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  creatorStepDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.ink,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  creatorStepDotText: {
    color: '#fff',
    fontFamily: fonts.displayBold,
    fontSize: 12,
    lineHeight: 12,
    textTransform: 'uppercase',
  },
  creatorStepText: {
    color: colors.inkSoft,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
    lineHeight: 18,
    flex: 1,
  },
  accountLinksRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 18,
  },
  accountLinkText: {
    color: colors.inkFaint,
    fontFamily: fonts.bodySemi,
    fontSize: 13,
    textDecorationLine: 'underline',
  },
  tabBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.forest,
    borderTopColor: colors.ink,
    borderTopWidth: 2,
    flexDirection: 'row',
    paddingTop: 10,
    paddingHorizontal: 14,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 2,
    minHeight: 48,
    gap: 8,
  },
  tabIndicator: {
    width: 28,
    height: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  tabIndicatorActive: {
    width: 40,
    backgroundColor: colors.green,
  },
  tabText: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: fonts.label,
    fontSize: 12,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  tabTextActive: {
    color: colors.green,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.54)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: colors.bg,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: spacing.lg,
  },
  redemptionCard: {
    backgroundColor: colors.bg,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: spacing.lg,
    paddingTop: 12,
    paddingBottom: 28,
  },
  swipeHandleWrap: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingBottom: 10,
    paddingTop: 2,
    marginBottom: 4,
  },
  swipeHandle: {
    alignSelf: 'center',
    width: 52,
    height: 5,
    borderRadius: 999,
    backgroundColor: colors.borderStrong,
    marginBottom: 14,
  },
  modalTitle: {
    color: colors.ink,
    fontFamily: fonts.display,
    fontSize: 34,
    letterSpacing: -0.2,
    lineHeight: 34,
    marginBottom: spacing.sm,
    textTransform: 'uppercase',
  },
  textButton: {
    alignItems: 'center',
    padding: 14,
  },
  textButtonText: {
    color: colors.inkFaint,
    fontFamily: fonts.label,
    fontSize: 14,
    textTransform: 'uppercase',
  },
  codeBox: {
    alignItems: 'center',
    backgroundColor: colors.forest,
    borderRadius: 16,
    marginBottom: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
  },
  codeLabel: {
    color: colors.green,
    fontFamily: fonts.label,
    fontSize: 12,
    letterSpacing: 1.3,
    marginBottom: spacing.xs,
    textTransform: 'uppercase',
  },
  codeText: {
    color: '#fff',
    fontFamily: fonts.display,
    fontSize: 52,
    letterSpacing: 1.4,
    lineHeight: 54,
    marginBottom: spacing.xs,
  },
  codeTimer: {
    color: 'rgba(255,255,255,0.72)',
    fontFamily: fonts.label,
    fontSize: 13,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  codeProgressTrack: {
    width: '100%',
    height: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.14)',
    marginTop: 18,
    overflow: 'hidden',
  },
  codeProgressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: colors.green,
  },
  codeRulesRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 18,
    width: '100%',
  },
  codeRuleChip: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  codeRuleValue: {
    color: '#fff',
    fontFamily: fonts.displayBold,
    fontSize: 18,
    lineHeight: 18,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  codeRuleLabel: {
    color: 'rgba(255,255,255,0.62)',
    fontFamily: fonts.label,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  redemptionHelp: {
    color: colors.inkSoft,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 20,
    textAlign: 'center',
  },
  redemptionActions: {
    gap: 14,
  },
  successCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 20,
  },
  successCheck: {
    color: '#fff',
    fontFamily: fonts.displayBold,
    fontSize: 38,
    lineHeight: 38,
    textTransform: 'uppercase',
  },
  actionCaption: {
    color: colors.inkFaint,
    fontFamily: fonts.label,
    fontSize: 12,
    letterSpacing: 1.2,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  holdCloseButton: {
    position: 'relative',
    minHeight: 56,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: colors.borderStrong,
    backgroundColor: colors.bg2,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  holdCloseProgress: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: colors.greenLight,
  },
  holdCloseText: {
    color: colors.ink,
    fontFamily: fonts.label,
    fontSize: 13,
    letterSpacing: 1.1,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
})
